version: '3'

services:  
  web:
    build: "."
    command: python -u airquality_live.py           
    restart: always     
    external_links:
      - postgres
    networks:
      - mynet

networks:
  mynet:
    external:
      name: mynet      
    # restart: "unless-stopped"          